# Generated by Django 5.2.8 on 2025-12-09 20:04

import django.db.models.deletion
import planning_poker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.CharField(default=planning_poker.models.Session.generate_six_digit_code, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('stories', models.JSONField()),
                ('mode_de_jeu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('carte_choisie', models.CharField(blank=True, max_length=10, null=True)),
                ('a_vote', models.BooleanField(default=False)),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning_poker.session')),
            ],
        ),
    ]
