# Generated by Django 5.2.8 on 2025-12-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='session',
            name='valeur',
        ),
        migrations.AddField(
            model_name='session',
            name='stories',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='session',
            table=None,
        ),
    ]
