# Generated by Django 5.2.8 on 2025-12-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partie',
            unique_together={('username', 'id_session')},
        ),
    ]
