# Generated by Django 5.2.8 on 2025-12-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0002_alter_partie_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
