# Generated by Django 5.2.8 on 2025-12-02 15:30

import planning_poker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0002_remove_session_contenu_remove_session_valeur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id_unique',
        ),
        migrations.AddField(
            model_name='session',
            name='id_session',
            field=models.CharField(default=planning_poker.models.Session.generate_six_digit_code, editable=False, max_length=6, unique=True),
        ),
    ]
