# Generated by Django 5.2.8 on 2025-12-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0003_remove_session_id_unique_session_id_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mode_de_jeu',
            field=models.CharField(default='strict', max_length=50),
            preserve_default=False,
        ),
    ]
