# Generated by Django 5.2.8 on 2025-12-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0003_session_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partie',
            name='a_vote',
        ),
        migrations.RemoveField(
            model_name='partie',
            name='carte_choisie',
        ),
    ]
