# Generated by Django 5.2.8 on 2025-12-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0004_session_mode_de_jeu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('carte_choisie', models.CharField(blank=True, max_length=10, null=True)),
                ('a_vote', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning_poker.session')),
            ],
        ),
    ]
