# Generated by Django 5.2.8 on 2025-12-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0004_remove_partie_a_vote_remove_partie_carte_choisie'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='a_vote',
            field=models.BooleanField(default=False),
        ),
    ]
