# Generated by Django 5.2.8 on 2025-12-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0005_partie_a_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partie',
            name='a_vote',
        ),
        migrations.AddField(
            model_name='partie',
            name='carte_choisie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
